// Mocks generated by Mockito 5.4.2 from annotations
// in currency_btc/test/presentation/bloc/current_price_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:currency_btc/data/failure.dart' as _i6;
import 'package:currency_btc/domain/entities/current_price_entity.dart' as _i7;
import 'package:currency_btc/domain/repositories/api_repository.dart' as _i2;
import 'package:currency_btc/domain/usecases/get_current_price.dart' as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiRepository_0 extends _i1.SmartFake implements _i2.ApiRepository {
  _FakeApiRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCurrentPrice].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentPrice extends _i1.Mock implements _i4.GetCurrentPrice {
  MockGetCurrentPrice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiRepository get apiRepository => (super.noSuchMethod(
        Invocation.getter(#apiRepository),
        returnValue: _FakeApiRepository_0(
          this,
          Invocation.getter(#apiRepository),
        ),
      ) as _i2.ApiRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.CurrentPriceEntity>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.CurrentPriceEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.CurrentPriceEntity>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.CurrentPriceEntity>>);
}
